# use for first run golang:latest. Then use image with installed go dependencies
#FROM golang:latest
FROM switcher_base

WORKDIR /go/src/github.com/abuloichyk-sm/tcp-sqs-example
COPY go.mod ./
COPY go.sum ./
COPY switcher ./switcher
WORKDIR /go/src/github.com/abuloichyk-sm/tcp-sqs-example/switcher
COPY credentials /root/.aws/credentials
EXPOSE 80
RUN go build
CMD ["go", "run", "."]